### ISSUE TITLE
多个账号登陆问题

### ISSUE THREAD

**Issue by liuhao0813** [a466350665/smart-sso#28]
问一个问题，我一个是服务器端，一个是客户端，如果两个都跳转到登陆窗口，一个窗口先用admin登陆，一个窗口后用zhangsan登陆，所有回话的内容应该是后登陆的zhangsan为准，但是再不启用redis的情况下，目前的回话还是之前登陆的admin

不知道大家的使用redis是不是也有这个问题

![xuyvbb1s 3hc_9d23m22sd](https://user-images.githubusercontent.com/5961039/32585797-23799468-c53a-11e7-9cbb-1aa672317370.png)

![_8awbc ndqc _ 38z4u 6 l](https://user-images.githubusercontent.com/5961039/32585938-d9b27f42-c53a-11e7-9b3e-f1ff05c00cd3.png)

**Comment by baishier** [comment]
确实有这个问题。
